"""Render the pooled commitment transitions without changing their scoring."""

from typing import Any

LEVELS = ("nice_to_have", "optional", "recommended", "mandatory")
LABELS = ("Weak intent", "Optional", "Recommended", "Mandatory")
SOURCE_CUES = ("wish", "may", "should", "must/shall")


def percentage_label(value: float) -> str:
    """Keep rare observed transitions visible after display rounding."""
    return r"$<0.1\%$" if 0 < value < 0.05 else rf"{value:.1f}\%"


def render_tikz(
    matrix_rows: list[dict[str, Any]],
    accounting_rows: list[dict[str, Any]],
    model_count: int,
    cell_count: int,
) -> str:
    """Use pooled source denominators and draw only strict upward transitions."""

    def pooled(row: dict[str, Any]) -> bool:
        return all(row[key] == "all" for key in ("model", "dataset", "variant"))

    accounting = {row["source_modality"]: row for row in accounting_rows if pooled(row)}
    if set(accounting) != set(LEVELS):
        raise ValueError("The figure requires accounting for all four source levels")
    lines = [
        "% Generated by scripts/export_commitment_transitions.py. Do not edit counts.",
        rf"% Pooled across {model_count} models and {cell_count} benchmark cells.",
        r"\begin{tikzpicture}[",
        r"  x=\linewidth, y=1pt, font=\fontsize{9}{11}\selectfont,",
        r"  level/.style={align=center, inner xsep=0pt, inner ysep=3pt,",
        r"    text width=0.21\linewidth, minimum height=34pt},",
        r"  transition/.style={-{Latex[length=4pt,width=3.5pt]}, line width=0.7pt},",
        r"  rate/.style={fill=white, inner sep=2pt, font=\fontsize{10}{12}\selectfont},",
        r"]",
        r"\path[use as bounding box] (0,-67) rectangle (1,76);",
    ]
    for index, (level, label, cue) in enumerate(
        zip(LEVELS, LABELS, SOURCE_CUES, strict=True)
    ):
        count = int(accounting[level]["n_readable"])
        formatted_count = f"{count:,}".replace(",", "{,}")
        lines.append(
            rf"\node[level] (level{index}) at ({0.105 + index * (0.79 / 3):.3f},0) "
            rf"{{\textbf{{{label}}}\\({cue})\\$N={formatted_count}$}};"
        )
    for row in matrix_rows:
        if not pooled(row) or not int(row["n_strict"]):
            continue
        source = LEVELS.index(row["source_modality"])
        target = LEVELS.index(row["text_modality"])
        denominator = int(accounting[LEVELS[source]]["n_readable"])
        if target <= source or denominator <= 0:
            raise ValueError(
                "Strict arrows require an upward transition and a denominator"
            )
        rate = percentage_label(100 * int(row["n_strict"]) / denominator)
        frame_only = source == 0 and target == 1
        style = ", dashed" if frame_only else ""
        side = "north" if source == 0 else "south"
        height = (22 if source == 0 else -18) * (target - source)
        lines.append(
            rf"\draw[transition{style}] (level{source}.{side}) "
            rf".. controls +(0,{height}) and +(0,{height}) .. "
            rf"node[rate, midway] {{{rate}}} (level{target}.{side});"
        )
    lines.extend(
        [
            r"\draw[transition] (0.05,-61) -- (0.10,-61);",
            r"\node[anchor=west, inner sep=2pt] at (0.11,-61) {Stronger modal wording};",
            r"\draw[transition, dashed] (0.55,-61) -- (0.60,-61);",
            r"\node[anchor=west, inner sep=2pt] at (0.61,-61) {Wish framing removed};",
            r"\end{tikzpicture}",
            "",
        ]
    )
    return "\n".join(lines)
